import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./button.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
<div className="button-container flex flex-row justify-center gap-4 p-4 items-center ml-auto mr-auto mt-4">
  <button className="button">
          <Link
            href="/"
            className="">
            Home
          </Link>
  </button>
  <button className="button">
    <Link
      href="/quotes"
    >
      Quotes
    </Link>
  </button>
  <button className="button">
          <Link
            href="/blog">
            Blog
          </Link>
  </button>

  <button className="button">
          <Link
            href="/about">
            About
          </Link>
  </button>
   <button className="button">
          <Link
            href="/store">
            store
          </Link>
  </button>
</div>

        <div className="flex gap-8 min-h-screen flex-row justify-center p-4">

          <div>

           </div>
           <div>
           
          </div>
          <div className="mt-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
